### ISSUE TITLE
Non-unified `update_or_create` on `StaticNetlink`

### ISSUE THREAD

**Issue by stdedos** [gabstopper/smc-python#21]
A related example would be:

`StaticNetlink.update_or_create([...])`

vs

`Router.update_or_create(filter_key={...}, [...])`

The "unified" syntax when used on `StaticNetlink` gives:

```python
Traceback (most recent call last):
  File "[...].py", line 238, in <module>
    add_routers_netlinks()
  File "[...].py", line 178, in add_routers_netlinks
    StaticNetlink.update_or_create(filter_key={[...]}, [...]).add_category([TAG_NAME])
  File "/home/sntentos/Documents/Forcepoint/PycharmProjects/createMLConfiguration/venv/lib/python3.5/site-packages/smc/elements/netlink.py", line 161, in update_or_create
    element.update()
  File "/home/sntentos/Documents/Forcepoint/PycharmProjects/createMLConfiguration/venv/lib/python3.5/site-packages/smc/base/model.py", line 427, in update
    result = request.update()
  File "/home/sntentos/Documents/Forcepoint/PycharmProjects/createMLConfiguration/venv/lib/python3.5/site-packages/smc/api/common.py", line 87, in update
    return self._make_request(method='PUT')
  File "/home/sntentos/Documents/Forcepoint/PycharmProjects/createMLConfiguration/venv/lib/python3.5/site-packages/smc/api/common.py", line 47, in _make_request
    raise err
smc.api.exceptions.UpdateElementFailed: Invalid JSON format: At line 1 and column 376, filter_key is not recognized as JSON attribute.

````

whereas, `Router` works as expected.

---
_I would kinda agree_ that on the usual case (e.g. searching by name, or IP address or whatever), you needn't specify a full `filter` dictionary (simply provide `key`(s), and get the value from the function arguments).

_Moreover_, on `name`-only comparison, you needn't even specify anything (just take it from the provided or "auto-created" name).

_However,_ I've never designed an API or a middle man :grin:

**Comment by gabstopper** [comment]
Aha, I was hoping you wouldnt notice the StaticNetlink yet.. :D. I'm not quite finished with that part. I whacked that in quickly to accomodate a request within ansible. This will get fixed/updated along with the interfaces kwargs later today. Thanks for the feedback!

**Comment by stdedos** [comment]
:grinning: I am sorry. The only reason I got involved with the API was, ultimately, Multilinks :wink:

**Comment by gabstopper** [comment]
No problem. On this subject, I have been luke warm about using filter_key at all. It was implemented to work around searches where the match needs to be very specific, typically for a key attribute that is not normally returned through the SMC search API. In particular networks/address ranges are somewhat challenging because / and - are reserved by the API and therefore only returned if they exist as part of the name. I have been considering dropping filter_key entirely.
BTW the name is always required and therefore using {'filter_key': name} is redundant and not required. An example of using filter key would be something like:
```python
Network.get_or_create(filter_key={'ipv4_network': '172.18.1.0/24'}, name='foo', ipv4_network='172.18.1.0/24')
```
In this scenario, unless the value '172.18.1.0/24' is part of the elements name, the SMC search API will not return it. So the search in more generic, then returned elements are also retrieved until a final match is found. This results in additional queries against the SMC versus the metadata returned in a normal search query. 

Ultimately I need to make a decision on filter_key but will implement it in staticnetlink for now for consistency.

Also, StaticNetlink and Multilink is implemented, but since I haven't seen much use of that area of code any feedback would help as I can improve the usability aspect.

**Comment by stdedos** [comment]
Well, I'd say deprecating code that's still working _and_ halfway usefull is not necessary.

Skipping it, I'd expect that it matches against only name probably?
It would be too much to require total match on missing `filter_key` (since name is unique across same name elements?).

_It is possible that `get_or_create` could require a complete match, whereas `update_or_create` partially matches and then aligns the element. Then `get_or_create` crashes if a same-name, different content element is found (or replaces it with the appopriate parameter / global set)_ - but I don't know. I think that would complicate the API too much. 😕

---

> Also, StaticNetlink and Multilink is implemented, but since I haven't seen much use of that area of code any feedback would help as I can improve the usability aspect.

You've noticed I haven't stopped opening issues 😀
Rest assured I'll continue if I find something

**Comment by gabstopper** [comment]
Correct. Without filter_key the match is only done by name, but the search is still filtered using a filter context by the element type. For example, Host.get_or_create, Host.update_or_create, Host('foo'), etc - all perform a default search logic of "search for a host with name = 'foo'". This could possibly return multiple matches, i.e. if you search for 'foo' with an exact match, you might return hosts 'foo', 'foo1', 'foo2'. But if you only want the entry that has an IP address of '1.1.1.1', you might use filter_key.

Please do report any other found issues. I will have the routing changes / static netlink cleaned up by Monday in a new commit.

**Comment by stdedos** [comment]
> if you search for 'foo' with an exact match, you might return hosts 'foo', 'foo1', 'foo2'

When I hear that, I think that

```python
len([i for i in hosts_object_list if i.name == 'foo'])
```

is `> 1`! Is that possible?
Doesn't exact match mean `i.name == 'foo'` whereas "non-exact" match means `'foo' in i.name`?

**Comment by stdedos** [comment]
Good to know in the future!

Thank you for going through the trouble to give out concrete and detailed examples. 😄 

_That should also go in a Wiki page, even if Copy/Pasted only_

**Comment by stdedos** [comment]
_I guess we technically resolved this. Leaving open as a Migrate-Helpful-Bits-to-Wiki_

**Comment by gabstopper** [comment]
Sounds good. I will build a wiki for bits of info just like this.

**Comment by gabstopper** [comment]
I've decided i'm going to remove filter_key from the Element based update_or_create. It will still be used if provided as kwarg, but originally it was added to handle searching for networks and ip range elements because of SMC API restrictions when searching using '/' or '-'.  In the case of network or ip_range, if the name did not contain the searchable char, it would not be returned.
For example, a network element:

'mynetwork' with value '1.1.1.0/24' would not be returned when searching only for 1.1.1.0/24. 

So filter_key provided a way to specify an internal attribute to match against. Note that this also meant that a fetch was required for every element beyond the initial metadata returned. 

To make a long story short, i'll likely document this in the method parameters but remove the hard coded definition from the update_or_create. I have seen this misused and the only side effect is that the SMC will incur more fetch processing.

**Comment by gabstopper** [comment]
One last thing - to further explain why it was implemented, you can see by doing a search in the SMC under networks.
I have a network with name 'someothernetwork' and an address of 192.168.11.0/24.

You can search for the element up to the '/' char:

![image](https://user-images.githubusercontent.com/14811349/42425277-b02e3436-82e0-11e8-916c-5af2e9520f7e.png)

Then when typing '/', you lose the match:

![image](https://user-images.githubusercontent.com/14811349/42425295-d9381c0c-82e0-11e8-9433-aab1c2d8c831.png)

Now note that IF the '/' is in the NAME field of the element then the matching succeeds. 

![image](https://user-images.githubusercontent.com/14811349/42425302-f2434f8c-82e0-11e8-8339-76a8d39b40bc.png)

This same logic applies to IP range elements as well. 
Regardless, the filter_key logic would be like this:

Network.get_or_create(filter_key={'ipv4_network': '192.168.11.0/24'}, name='someothernetwork', ipv4_network='192.168.11.0/24')

The initial search would be done on the filter attribute value, but in the case of ipv4_network, the search woud be set to '192.168.11.0'.
The results would then each be fetched until 192.168.11.0/24 was found.

**Comment by stdedos** [comment]
@gabstopper I assume that this
> I've decided i'm going to remove filter_key from the Element based update_or_create
has been already processed?

I guess I am fine closing the ticket, since I cannot find `filter_key` anywhere on my code

**Comment by gabstopper** [comment]
ok will close. Note that this is still possible to use if need be and I do use it when searching Networks including '/' in the search and AddressRanges when '-' is provided. But otherwise it's generally not needed.
